import { openai, supabase } from "./config.js";

// User query about content in the database
const query = "Decoding orca calls";

/*
  Create an embedding from the user input and return a 
  semantically matching text chunk from the database 
*/
async function main(input) {
  // Create a vector embedding representing the input text
  const embeddingResponse = await openai.embeddings.create({
    model: process.env.AI_MODEL,
    input,
    dimensions: 1536, //ai model default embedding size 3072
  });

  // The vector generated by OpenAI
  const embedding = embeddingResponse.data[0].embedding;
  // Query Supabase for nearest vector match
  const { data } = await supabase.rpc("match_documents", {
    query_embedding: embedding,
    match_threshold: 0.1, // ৫০% এর বেশি মিল থাকলে রেজাল্ট দেখাবে
    match_count: 3, // সেরা ৫টি রেজাল্ট দেখাবে
  });
  // console.log(data);
  console.log(data[0].content, data[0].similarity);
}
main(query);
